language: ruby

rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
env:
  matrix:
    - INTEGRATE_WITH=default
    - INTEGRATE_WITH=1.8.7
  global:
    # target
    - secure: "PVuHeyua/eEtGQamnfE7Q7IlPlqOQWGUBX9oXnXABXbyVnIlty8H4vp5ugSy\nBytcWvUHPDYSa8yypcwl8kWCc6/x4oGD8JUCz8RsSPhzML9fgNLqhPxe1TVQ\niDW5hF2tb6NPzLP4zv/iD2F1ojUN6Xw6UIsPHiay0yf4EwxS6kY="
    # user
    - secure: "CCzP2Zgjq3CkMnFZxJCiHuUV7oubKy2iNiBwA+Q72WpCyKCf1rp3vtGU4+2R\n9rgns0FQfwYVz5ePVHnUkJWh5xwBA65quo9d8AoFmDftJQhRAvrDlXYZ7VtR\nx5yR6Ohqi61y1fZOSo0Wm7w4jzXJ8gVwZlkMXpOaurRpkre+4+s="
    # pw
    - secure: "Fsq1lJsY9PC+jIhHYIeATB0mfDL36D1ZNb/9bCBEYdumgnDSSBKxiFCcPMm/\n/UiHw//72XOz/SmcWeUgDEU50xOP5lo9hyrsILJwmgIkX+ToC5Rf09ATqxq3\nxgg8MrNAIQ74nRzg6FGrw7OTNRJeeSfsbGcpVZaNSSxhNEoVT6k="
    # other user
    - secure: "jDNIuEe7xk+sm0qKL4+3UzlPlhlLHeOeJRpHJCORyPUyx0o8W5SKCDb7u/GX\n9HD/47A1IozfRuQR+iD4NUu/VUtFYDWF8k5idtih757MMLAOVwezcMPlJTRA\nqjiRxCB7RQSevs0VEP+DnljDCs3jnHHjdwMtum3DngV/VTUZ4YU="
    # other pw
    - secure: "QJggOq2NcdrVTB2z2VeLcVwUhuJrzdVx8yxwrU2iWXnBnClVYeH7JWVVxeHd\n78S16hMqoxML03wjyBJy6uYBWjSGWxEZ+ZAWxJAzU3f5XO46cLC54UX8+P2F\nkdS8UkzekQMnLcXAt5RO888+Ggu1NosTgjekRZgzW4kk1EM+W/g="
    # other space
    - secure: "eQY5TYHpiYFWfWJSX0GJBiQu9U2UyLtbLXfUNZSNU4ZMSc8gLG10GSDPzoiw\nYjhN/O0RZChRapnDkyFz3dDRCedlRIR4S+JCnYp3ZG90pVqw2Pz1uBdCzRbL\n0FRwr+YNwzwcuaT6IFFv6S+AFh+xITKYvmNHDQItIdEMxgByNn0="
    # other org
    - secure: "Bd6/fDgEkCqdo6zx0OXlis7b+x2MDfCOSy33hk2MsOZxygHM1gDRdjpcshIr\ngKJG3el6xb9WfRv1aaYXl13zoepxbA2q8fQUrmIMtoMUiWsSfBtpjjccYvfW\nkg41LhBGSdYqkn/b/b1oQDIE9BqbLxR056iDdwnk9XV6UDfp7Ns="

before_script: ./script/setup_187

matrix:
  exclude:
    - rvm: 1.8.7
      env: INTEGRATE_WITH=1.8.7
    - rvm: 1.9.2
      env: INTEGRATE_WITH=1.8.7
